# Key settings (must edit)
project_title: Choochoo test repository
project_repo: nu-cem/choochoo-test
admins:
- lucydot
instructors:
- lucydot
students:
- lucydot
web_address: https://nu-cem.github.io/choochoo-test

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true
gh-pages_branch: gh-pages



